#!/usr/bin/env python3
"""Generate a country-grouped affiliation treemap from the current paper dataset."""

from __future__ import annotations

import argparse
import colorsys
import math
import tempfile
import textwrap
from pathlib import Path

import pandas as pd

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
from matplotlib import colors as mcolors
from matplotlib import patches
import squarify


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build a country-grouped affiliation treemap from papers.csv, using "
            "author affiliation data from authors_orcid_subgraph.csv."
        )
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=Path("data/dblp_ai_authors_2015_2025"),
        help="Directory containing papers.csv, authors_orcid_subgraph.csv, and affiliation_country_lookup.csv.",
    )
    parser.add_argument(
        "--papers-csv",
        type=Path,
        default=None,
        help="Override papers CSV path. Defaults to <input-dir>/papers.csv.",
    )
    parser.add_argument(
        "--authors-csv",
        type=Path,
        default=None,
        help="Override author affiliation CSV path. Defaults to <input-dir>/authors_orcid_subgraph.csv.",
    )
    parser.add_argument(
        "--country-lookup-csv",
        type=Path,
        default=None,
        help="Override affiliation-country lookup CSV path. Defaults to <input-dir>/affiliation_country_lookup.csv.",
    )
    parser.add_argument(
        "--output-png",
        type=Path,
        default=None,
        help="Output PNG path. Defaults to <input-dir>/results/<auto-generated-name>.png.",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=None,
        help="Output CSV path. Defaults to <input-dir>/results/<auto-generated-name>.csv.",
    )
    parser.add_argument(
        "--count-mode",
        choices=["paper", "authorship"],
        default="paper",
        help=(
            "'paper' counts each paper at most once per affiliation; "
            "'authorship' counts every paper-author affiliation incidence."
        ),
    )
    parser.add_argument(
        "--author-scope",
        choices=["all", "first"],
        default="all",
        help=(
            "'all' considers every author on each paper; "
            "'first' only considers the first listed author on each paper."
        ),
    )
    parser.add_argument(
        "--top-countries",
        type=int,
        default=12,
        help="Keep the top-N countries by paper count in the treemap.",
    )
    parser.add_argument(
        "--top-affiliations-per-country",
        type=int,
        default=20,
        help="Keep the top-N affiliations within each country in the treemap.",
    )
    parser.add_argument(
        "--min-paper-count",
        type=int,
        default=1,
        help="Drop affiliations with fewer than this many counted papers before plotting.",
    )
    parser.add_argument(
        "--figure-width",
        type=float,
        default=16.0,
        help="Figure width in inches.",
    )
    parser.add_argument(
        "--figure-height",
        type=float,
        default=10.0,
        help="Figure height in inches.",
    )
    return parser.parse_args()


def split_pipe(value: object) -> list[str]:
    return [part.strip() for part in str(value or "").split("|") if part.strip()]


def default_output_stem(authors_csv: Path, author_scope: str) -> str:
    stem = authors_csv.stem
    if stem == "authors_orcid_subgraph":
        return (
            "affiliation_paper_count_treemap"
            if author_scope == "all"
            else "affiliation_paper_count_treemap_first_author"
        )
    if stem == "authors_orcid_fullgraph":
        return (
            "affiliation_paper_count_treemap_fullgraph"
            if author_scope == "all"
            else "affiliation_paper_count_treemap_fullgraph_first_author"
        )

    suffix = stem.removeprefix("authors_")
    if author_scope == "first":
        suffix = f"{suffix}_first_author"
    return f"affiliation_paper_count_treemap_{suffix}"


def load_author_affiliations(authors_csv: Path, country_lookup_csv: Path) -> dict[str, dict[str, str]]:
    authors_df = pd.read_csv(authors_csv, low_memory=False).fillna("")
    lookup_df = pd.read_csv(country_lookup_csv, low_memory=False).fillna("")

    affiliation_to_country = {
        str(row.affiliation_label).strip(): {
            "country_code": str(row.country_code).strip(),
            "country_name": str(row.country_name).strip(),
        }
        for row in lookup_df.itertuples(index=False)
        if str(row.affiliation_label).strip()
    }

    code_to_country_name: dict[str, str] = {}
    for row in lookup_df.itertuples(index=False):
        code = str(row.country_code).strip()
        name = str(row.country_name).strip()
        if code and name and code not in code_to_country_name:
            code_to_country_name[code] = name

    author_map: dict[str, dict[str, str]] = {}
    for row in authors_df.itertuples(index=False):
        author_id = str(getattr(row, "author_id", "")).strip()
        affiliation = str(getattr(row, "affiliation", "")).strip()
        if not author_id or not affiliation:
            continue

        country_code = str(getattr(row, "affiliation_country_code", "")).strip()
        country_name = code_to_country_name.get(country_code, "")

        if not country_name:
            lookup_entry = affiliation_to_country.get(affiliation, {})
            country_code = country_code or lookup_entry.get("country_code", "")
            country_name = lookup_entry.get("country_name", "")

        if not country_name:
            country_name = "Unknown"
        if not country_code:
            country_code = "UNK" if country_name == "Unknown" else country_name[:3].upper()

        author_map[author_id] = {
            "affiliation": affiliation,
            "country_code": country_code,
            "country_name": country_name,
        }

    return author_map


def build_affiliation_counts(
    papers_csv: Path,
    author_map: dict[str, dict[str, str]],
    count_mode: str,
    author_scope: str,
) -> tuple[pd.DataFrame, dict[str, int]]:
    papers_df = pd.read_csv(papers_csv, low_memory=False).fillna("")

    affiliation_counts: dict[tuple[str, str], int] = {}
    country_counts: dict[str, int] = {}

    total_papers = 0
    papers_with_any_mapped_author = 0
    mapped_author_mentions = 0
    unmapped_author_mentions = 0
    total_author_mentions = 0
    unique_mapped_authors: set[str] = set()

    for row in papers_df.itertuples(index=False):
        total_papers += 1
        author_ids = split_pipe(getattr(row, "author_ids", ""))
        if author_scope == "first":
            author_ids = author_ids[:1]
        total_author_mentions += len(author_ids)

        mapped_entries: list[tuple[str, str]] = []
        for author_id in author_ids:
            metadata = author_map.get(author_id)
            if metadata is None:
                unmapped_author_mentions += 1
                continue
            mapped_author_mentions += 1
            unique_mapped_authors.add(author_id)
            mapped_entries.append((metadata["country_name"], metadata["affiliation"]))

        if mapped_entries:
            papers_with_any_mapped_author += 1

        if count_mode == "paper":
            mapped_entries = sorted(set(mapped_entries))

        for country_name, affiliation in mapped_entries:
            key = (country_name, affiliation)
            affiliation_counts[key] = affiliation_counts.get(key, 0) + 1
            country_counts[country_name] = country_counts.get(country_name, 0) + 1

    rows = [
        {
            "country_name": country_name,
            "affiliation": affiliation,
            "paper_count": count,
        }
        for (country_name, affiliation), count in affiliation_counts.items()
    ]
    counts_df = pd.DataFrame(rows).sort_values(
        by=["paper_count", "country_name", "affiliation"],
        ascending=[False, True, True],
    )
    coverage = {
        "total_papers": total_papers,
        "papers_with_any_mapped_author": papers_with_any_mapped_author,
        "total_author_mentions": total_author_mentions,
        "mapped_author_mentions": mapped_author_mentions,
        "unmapped_author_mentions": unmapped_author_mentions,
        "mapped_unique_authors": len(unique_mapped_authors),
        "authors_with_affiliation_metadata": len(author_map),
        "author_scope": author_scope,
    }
    return counts_df, coverage


def apply_plot_filters(
    counts_df: pd.DataFrame,
    top_countries: int,
    top_affiliations_per_country: int,
    min_paper_count: int,
) -> pd.DataFrame:
    filtered = counts_df.loc[counts_df["paper_count"] >= min_paper_count].copy()
    if filtered.empty:
        return filtered

    country_totals = (
        filtered.groupby("country_name", as_index=False)["paper_count"]
        .sum()
        .sort_values(by=["paper_count", "country_name"], ascending=[False, True])
    )
    keep_countries = set(country_totals.head(top_countries)["country_name"].tolist())
    filtered = filtered.loc[filtered["country_name"].isin(keep_countries)].copy()

    trimmed_frames = []
    for country_name, group in filtered.groupby("country_name", sort=False):
        trimmed = group.sort_values(
            by=["paper_count", "affiliation"],
            ascending=[False, True],
        ).head(top_affiliations_per_country)
        trimmed_frames.append(trimmed)

    result = pd.concat(trimmed_frames, ignore_index=True) if trimmed_frames else filtered.iloc[0:0].copy()
    return result.sort_values(
        by=["country_name", "paper_count", "affiliation"],
        ascending=[True, False, True],
    )


def build_palette(names: list[str]) -> dict[str, str]:
    base_colors = [
        "#d24b40",
        "#5388c7",
        "#ff9933",
        "#9a78c9",
        "#61c2d4",
        "#59a541",
        "#9a7a6a",
        "#7cc84e",
        "#d1a34a",
        "#5d9d89",
        "#8479d9",
        "#c65d91",
    ]
    return {
        name: base_colors[index % len(base_colors)]
        for index, name in enumerate(names)
    }


def adjust_color(hex_color: str, factor: float) -> tuple[float, float, float]:
    red, green, blue = mcolors.to_rgb(hex_color)
    hue, lightness, saturation = colorsys.rgb_to_hls(red, green, blue)
    lightness = max(0.15, min(0.85, lightness * factor))
    return colorsys.hls_to_rgb(hue, lightness, saturation)


def fit_label(text: str, max_chars: int) -> str:
    words = text.split()
    if not words:
        return text
    return "\n".join(textwrap.wrap(text, width=max(6, max_chars), break_long_words=False))


def draw_treemap(plot_df: pd.DataFrame, output_png: Path, figure_width: float, figure_height: float) -> None:
    total_count = int(plot_df["paper_count"].sum())
    country_totals = (
        plot_df.groupby("country_name", as_index=False)["paper_count"]
        .sum()
        .sort_values(by=["paper_count", "country_name"], ascending=[False, True])
    )
    country_palette = build_palette(country_totals["country_name"].tolist())

    top_sizes = country_totals["paper_count"].tolist()
    top_rects = squarify.squarify(
        squarify.normalize_sizes(top_sizes, 100, 100),
        0,
        0,
        100,
        100,
    )

    plt.figure(figsize=(figure_width, figure_height))
    ax = plt.gca()
    ax.set_xlim(0, 100)
    ax.set_ylim(0, 100)
    ax.invert_yaxis()
    ax.axis("off")
    ax.set_facecolor("white")

    for country_row, country_rect in zip(country_totals.itertuples(index=False), top_rects):
        country_name = str(country_row.country_name)
        country_total = int(country_row.paper_count)
        base_color = country_palette[country_name]

        x_coord = country_rect["x"]
        y_coord = country_rect["y"]
        width = country_rect["dx"]
        height = country_rect["dy"]
        area = width * height
        if area <= 0:
            continue

        title_band = min(max(height * 0.10, 2.0), 6.0)
        body_y = y_coord + title_band
        body_height = max(0.5, height - title_band)

        ax.add_patch(
            patches.Rectangle(
                (x_coord, y_coord),
                width,
                height,
                facecolor=adjust_color(base_color, 1.20),
                edgecolor="white",
                linewidth=2.5,
            )
        )

        country_percent = country_total / total_count * 100.0 if total_count else 0.0
        title_text = f"{country_name}  ·  {country_percent:.1f}%"
        font_size = max(8, min(19, 6.5 + 0.16 * math.sqrt(area)))
        ax.text(
            x_coord + 0.8,
            y_coord + title_band * 0.65,
            title_text,
            ha="left",
            va="center",
            fontsize=font_size,
            fontweight="bold",
            color="#111111",
        )

        country_affiliations = plot_df.loc[plot_df["country_name"] == country_name].sort_values(
            by=["paper_count", "affiliation"],
            ascending=[False, True],
        )
        aff_sizes = country_affiliations["paper_count"].tolist()
        aff_rects = squarify.squarify(
            squarify.normalize_sizes(aff_sizes, width, body_height),
            x_coord,
            body_y,
            width,
            body_height,
        )

        aff_count = max(1, len(country_affiliations))
        for index, (aff_row, aff_rect) in enumerate(zip(country_affiliations.itertuples(index=False), aff_rects)):
            aff_x = aff_rect["x"]
            aff_y = aff_rect["y"]
            aff_w = aff_rect["dx"]
            aff_h = aff_rect["dy"]
            aff_area = aff_w * aff_h
            if aff_area <= 0:
                continue

            brightness = 0.92 - (0.22 * (index / max(1, aff_count - 1)))
            fill_color = adjust_color(base_color, brightness)

            ax.add_patch(
                patches.Rectangle(
                    (aff_x, aff_y),
                    aff_w,
                    aff_h,
                    facecolor=fill_color,
                    edgecolor="white",
                    linewidth=1.2,
                )
            )

            if aff_w < 4 or aff_h < 3 or aff_area < 20:
                continue

            affiliation = str(aff_row.affiliation)
            affiliation_percent = int(aff_row.paper_count) / total_count * 100.0 if total_count else 0.0
            aff_font = max(7, min(18, 5.0 + 0.11 * math.sqrt(aff_area)))
            max_chars = max(8, int(aff_w * 1.15))
            label = fit_label(affiliation, max_chars=max_chars)

            lines = [label]
            if aff_area > 65:
                lines.append(f"{affiliation_percent:.1f}%  ({int(aff_row.paper_count)})")
            elif aff_area > 35:
                lines.append(f"{int(aff_row.paper_count)}")

            ax.text(
                aff_x + aff_w / 2,
                aff_y + aff_h / 2,
                "\n".join(lines),
                ha="center",
                va="center",
                fontsize=aff_font,
                fontweight="bold",
                color="white",
                linespacing=1.1,
            )

    plt.tight_layout(pad=0.6)
    output_png.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_png, dpi=240, bbox_inches="tight", facecolor="white")
    plt.close()


def main() -> None:
    args = parse_args()
    papers_csv = args.papers_csv or (args.input_dir / "papers.csv")
    authors_csv = args.authors_csv or (args.input_dir / "authors_orcid_subgraph.csv")
    country_lookup_csv = args.country_lookup_csv or (args.input_dir / "affiliation_country_lookup.csv")
    default_stem = default_output_stem(authors_csv, args.author_scope)
    results_dir = args.input_dir / "results"
    output_png = args.output_png or (results_dir / f"{default_stem}.png")
    output_csv = args.output_csv or (results_dir / f"{default_stem}.csv")

    if not papers_csv.exists():
        raise SystemExit(f"Missing papers CSV: {papers_csv}")
    if not authors_csv.exists():
        raise SystemExit(f"Missing authors CSV: {authors_csv}")
    if not country_lookup_csv.exists():
        raise SystemExit(f"Missing country lookup CSV: {country_lookup_csv}")

    author_map = load_author_affiliations(authors_csv, country_lookup_csv)
    counts_df, coverage = build_affiliation_counts(
        papers_csv=papers_csv,
        author_map=author_map,
        count_mode=args.count_mode,
        author_scope=args.author_scope,
    )
    if counts_df.empty:
        raise SystemExit("No affiliation counts could be built from the current data.")

    plot_df = apply_plot_filters(
        counts_df=counts_df,
        top_countries=args.top_countries,
        top_affiliations_per_country=args.top_affiliations_per_country,
        min_paper_count=args.min_paper_count,
    )
    if plot_df.empty:
        raise SystemExit("All affiliation rows were filtered out. Lower --min-paper-count or raise the top-N limits.")

    plot_country_totals = (
        plot_df.groupby("country_name", as_index=False)["paper_count"]
        .sum()
        .sort_values(by=["paper_count", "country_name"], ascending=[False, True])
    )
    plot_df = plot_df.merge(
        plot_country_totals.rename(columns={"paper_count": "country_paper_count"}),
        on="country_name",
        how="left",
    )
    plot_total = int(plot_df["paper_count"].sum())
    plot_df["global_share_percent"] = plot_df["paper_count"] / plot_total * 100.0
    plot_df["country_share_percent"] = plot_df["paper_count"] / plot_df["country_paper_count"] * 100.0
    plot_df = plot_df.sort_values(
        by=["country_paper_count", "paper_count", "country_name", "affiliation"],
        ascending=[False, False, True, True],
    )

    output_csv.parent.mkdir(parents=True, exist_ok=True)
    plot_df.to_csv(output_csv, index=False, encoding="utf-8")
    draw_treemap(
        plot_df=plot_df,
        output_png=output_png,
        figure_width=args.figure_width,
        figure_height=args.figure_height,
    )

    mapped_ratio = (
        coverage["mapped_author_mentions"] / coverage["total_author_mentions"] * 100.0
        if coverage["total_author_mentions"]
        else 0.0
    )
    paper_ratio = (
        coverage["papers_with_any_mapped_author"] / coverage["total_papers"] * 100.0
        if coverage["total_papers"]
        else 0.0
    )

    print(f"Saved treemap PNG to {output_png}")
    print(f"Saved treemap counts CSV to {output_csv}")
    print(
        "[coverage] "
        f"author_scope={coverage['author_scope']} | "
        f"authors_with_affiliation_metadata={coverage['authors_with_affiliation_metadata']} | "
        f"mapped_unique_authors={coverage['mapped_unique_authors']} | "
        f"mapped_author_mentions={coverage['mapped_author_mentions']} / {coverage['total_author_mentions']} "
        f"({mapped_ratio:.2f}%) | "
        f"papers_with_any_mapped_author={coverage['papers_with_any_mapped_author']} / {coverage['total_papers']} "
        f"({paper_ratio:.2f}%)"
    )
    print(
        "[plot] "
        f"countries={plot_df['country_name'].nunique()} | "
        f"affiliations={plot_df.shape[0]} | "
        f"plot_total_paper_count={plot_total}"
    )


if __name__ == "__main__":
    main()
