#!/usr/bin/env python3
"""Manual affiliation -> country overrides for unresolved organization labels."""

from __future__ import annotations


MANUAL_AFFILIATION_COUNTRY_OVERRIDES: dict[str, dict[str, str]] = {
    "Art Institute of Portland": {
        "ror_id": "",
        "ror_name": "Art Institute of Portland",
        "country_code": "US",
        "country_name": "United States",
        "match_status": "manual",
    },
    "Ben-Gurion University of the Negev": {
        "ror_id": "",
        "ror_name": "Ben-Gurion University of the Negev",
        "country_code": "IL",
        "country_name": "Israel",
        "match_status": "manual",
    },
    "Daimler (Germany)": {
        "ror_id": "",
        "ror_name": "Daimler",
        "country_code": "DE",
        "country_name": "Germany",
        "match_status": "manual",
    },
    "Fifth Affiliated Hospital of Sun Yat-sen University": {
        "ror_id": "",
        "ror_name": "Fifth Affiliated Hospital of Sun Yat-sen University",
        "country_code": "CN",
        "country_name": "China",
        "match_status": "manual",
    },
    "IBM Research (China)": {
        "ror_id": "",
        "ror_name": "IBM Research (China)",
        "country_code": "CN",
        "country_name": "China",
        "match_status": "manual",
    },
    "Inner Mongolia Agricultural University": {
        "ror_id": "",
        "ror_name": "Inner Mongolia Agricultural University",
        "country_code": "CN",
        "country_name": "China",
        "match_status": "manual",
    },
    "Inner Mongolia Maternal and Child Health": {
        "ror_id": "",
        "ror_name": "Inner Mongolia Maternal and Child Health",
        "country_code": "CN",
        "country_name": "China",
        "match_status": "manual",
    },
    "Inner Mongolia University": {
        "ror_id": "",
        "ror_name": "Inner Mongolia University",
        "country_code": "CN",
        "country_name": "China",
        "match_status": "manual",
    },
    "Inner Mongolia University of Technology": {
        "ror_id": "",
        "ror_name": "Inner Mongolia University of Technology",
        "country_code": "CN",
        "country_name": "China",
        "match_status": "manual",
    },
    "Institute of Geodesy and Geophysics": {
        "ror_id": "",
        "ror_name": "Institute of Geodesy and Geophysics",
        "country_code": "CN",
        "country_name": "China",
        "match_status": "manual",
    },
    "Institute of Hydrobiology, Biology Centre, Academy of Sciences of the Czech Republic": {
        "ror_id": "",
        "ror_name": "Institute of Hydrobiology, Biology Centre, Academy of Sciences of the Czech Republic",
        "country_code": "CZ",
        "country_name": "Czech Republic",
        "match_status": "manual",
    },
    "Istituto di Scienze Marine del Consiglio Nazionale delle Ricerche": {
        "ror_id": "",
        "ror_name": "Istituto di Scienze Marine del Consiglio Nazionale delle Ricerche",
        "country_code": "IT",
        "country_name": "Italy",
        "match_status": "manual",
    },
    "National Center for Infectious Diseases": {
        "ror_id": "",
        "ror_name": "National Centre for Infectious Diseases",
        "country_code": "SG",
        "country_name": "Singapore",
        "match_status": "manual",
    },
    "National Sun Yat-sen University": {
        "ror_id": "",
        "ror_name": "National Sun Yat-sen University",
        "country_code": "TW",
        "country_name": "Taiwan",
        "match_status": "manual",
    },
    "Sixth Affiliated Hospital of Sun Yat-sen University": {
        "ror_id": "",
        "ror_name": "Sixth Affiliated Hospital of Sun Yat-sen University",
        "country_code": "CN",
        "country_name": "China",
        "match_status": "manual",
    },
    "Sorbonne Paris Cité": {
        "ror_id": "",
        "ror_name": "Sorbonne Paris Cité",
        "country_code": "FR",
        "country_name": "France",
        "match_status": "manual",
    },
    "Sun Yat-sen Memorial Hospital": {
        "ror_id": "",
        "ror_name": "Sun Yat-sen Memorial Hospital",
        "country_code": "CN",
        "country_name": "China",
        "match_status": "manual",
    },
    "Sun Yat-sen University": {
        "ror_id": "",
        "ror_name": "Sun Yat-sen University",
        "country_code": "CN",
        "country_name": "China",
        "match_status": "manual",
    },
    "Sun Yat-sen University Cancer Center": {
        "ror_id": "",
        "ror_name": "Sun Yat-sen University Cancer Center",
        "country_code": "CN",
        "country_name": "China",
        "match_status": "manual",
    },
    "The First Affiliated Hospital, Sun Yat-sen University": {
        "ror_id": "",
        "ror_name": "The First Affiliated Hospital, Sun Yat-sen University",
        "country_code": "CN",
        "country_name": "China",
        "match_status": "manual",
    },
    "The Seventh Affiliated Hospital of Sun Yat-sen University": {
        "ror_id": "",
        "ror_name": "The Seventh Affiliated Hospital of Sun Yat-sen University",
        "country_code": "CN",
        "country_name": "China",
        "match_status": "manual",
    },
    "The University of Adelaide": {
        "ror_id": "",
        "ror_name": "University of Adelaide",
        "country_code": "AU",
        "country_name": "Australia",
        "match_status": "manual",
    },
    "University of Adelaide": {
        "ror_id": "",
        "ror_name": "University of Adelaide",
        "country_code": "AU",
        "country_name": "Australia",
        "match_status": "manual",
    },
    "Université Fédérale de Toulouse Midi-Pyrénées": {
        "ror_id": "",
        "ror_name": "Université Fédérale de Toulouse Midi-Pyrénées",
        "country_code": "FR",
        "country_name": "France",
        "match_status": "manual",
    },
    "Université Toulouse III - Paul Sabatier": {
        "ror_id": "",
        "ror_name": "Université Toulouse III - Paul Sabatier",
        "country_code": "FR",
        "country_name": "France",
        "match_status": "manual",
    },
    "Université Toulouse-I-Capitole": {
        "ror_id": "",
        "ror_name": "Université Toulouse-I-Capitole",
        "country_code": "FR",
        "country_name": "France",
        "match_status": "manual",
    },
}

